# Generated by Django 2.2.4 on 2019-08-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('device', models.CharField(max_length=30)),
                ('temperature', models.IntegerField()),
                ('crc_pass', models.BooleanField()),
                ('raw_data', models.TextField()),
            ],
        ),
    ]
