# Generated by Django 2.2.4 on 2019-08-17 17:53

from django.db import migrations, models
import django.db.models.deletion
from data.models import Device


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190817_1703'),
    ]

    def createDevices(apps, schema_operations):
        old_DataPoint = apps.get_model('data','DataPoint')
        Device.objects.bulk_create([
            Device(device=x,description='Added on migration') for x in old_DataPoint.objects.values_list('device', flat=True).distinct()
        ])

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(createDevices),
        migrations.AlterField(
            model_name='datapoint',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='data.Device', to_field='device'),
        ),
        migrations.AlterField(
            model_name='temperaturedatapoint',
            name='datapoint_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.DataPoint'),
        ),
    ]
