# Generated by Django 2.2.4 on 2019-08-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_alerts', '0002_auto_20190817_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertthreshold',
            old_name='current_data_point',
            new_name='current_datapoint',
        ),
    ]
