# Generated by Django 2.2.4 on 2019-08-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_email_mailinglist'),
        ('data_alerts', '0003_auto_20190817_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertfamily',
            name='mailinglists',
            field=models.ManyToManyField(related_name='mailing_lists', to='data.MailingList'),
        ),
    ]
