# Generated by Django 2.2.4 on 2019-08-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_email_mailinglist'),
        ('data_alerts', '0004_alertfamily_mailinglists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertfamily',
            name='mailinglists',
        ),
        migrations.AddField(
            model_name='alertfamily',
            name='mailing_lists',
            field=models.ManyToManyField(to='data.MailingList'),
        ),
    ]
